### ISSUE TITLE
Add UI controls for printing page

### ISSUE THREAD

**Issue by MGApcDev** [MGApcDev/mlTex#18]
### Notes
CSS for ignoring all other content
```css
@media print {
    body * {
        visibility: hidden;
    }
    .tex-document, .tex-document * {
        visibility: visible;
    }
    .tex-document {
        position: absolute;
        left: 0;
        top: 0;
    }
}
```

JavaScript for print only the content window (codepen iframe)

```js
$('body').click(function () {
    window.print();
});
```
