### ISSUE TITLE
Add UI controls for scaling page

### ISSUE THREAD

**Issue by MGApcDev** [MGApcDev/mlTex#22]
Use CSS [zoom](https://css-tricks.com/almanac/properties/z/zoom/) property, and combine with js to dynamically change property.
```css
.tex-document {
    zoom: 100%; // default
    -moz-transform: scale(1.0);
}
```
